services:
  - type: web
    name: ielts-platform
    rootDir: server
    env: node
    buildCommand: npm ci --production=false
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ielts-platform-two.vercel.app
      - key: BACKEND_URL
        value: https://ielts-platform-emrv.onrender.com
    region: singapore
    plan: free
